import './globals.css'
import localFont from 'next/font/local'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const unbounded = localFont({
  src: [
    {
      path: '../../public/fonts/Unbounded.ttf'
    }
  ],
  variable: '--font-unbounded'
})

const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat.ttf'
    }
  ],
  variable: '--font-montserrat'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${unbounded.variable} ${montserrat.variable} font-sans text-white bg-black`}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  )
}
