import './globals.css'
import localFont from 'next/font/local'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Language from "@/components/Language/Language";
import {DataDevelopContext, DataDevelopProvider} from "@/app/contexts/DataDevelopContext";

const unbounded = localFont({
  src: [
    {
      path: '../../public/fonts/Unbounded.ttf'
    }
  ],
  variable: '--font-unbounded'
})

const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat.ttf'
    }
  ],
  variable: '--font-montserrat'
})

const exo2 = localFont({
  src: [
    {
      path: '../../public/fonts/Exo2.ttf'
    }
  ],
  variable: '--font-exo2'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${unbounded.variable} ${montserrat.variable} ${exo2.variable} font-sans text-white bg-black`}>
      <DataDevelopProvider>
          <Header />
          <Language />
            {children}
          <Footer />
      </DataDevelopProvider>
      </body>
    </html>
  )
}
